### ISSUE TITLE
Busy loop in `getNextEvent()`

### ISSUE THREAD

**Issue by ShabbyX** [erikzenker/Inotify#1]
In `getNextEvent()`, you are busy-looping trying to read events:

```C
while(length <= 0 ){
	length = read(mInotifyFd, buffer, EVENT_BUF_LEN);
	currentEventTime = time(NULL);
	if(length == -1){
		mError = errno;
		if(mError != EINTR){
			continue;
		}
	}
}
```

You can use `select` or `poll` for example to sleep instead.

Also, try `clock_gettime()` instead of `time()` for a much better precision.

**Comment by erikzenker** [comment]
You mean to make to call non-blocking?

**Comment by ShabbyX** [comment]
That could be another function, but in this case, I meant you should "block" the process until there is an event, instead of busy-looping. With your current implementation, if it takes two hours for an event to arrive, you will have one cpu stuck at 100% waiting for it. That's not good.

**Comment by erikzenker** [comment]
As far as I know then calling `read` is blocking:
```c++
	length = read(mInotifyFd, buffer, EVENT_BUF_LEN);
```
Thus the while loop is not a busy-loop and does not consume 100% CPU when waiting for the next event. Or do I miss something?

**Comment by ShabbyX** [comment]
That would depend on how the fd was `open()`ed. Also, since this is a "special" files, `read()` is allowed to return 0 immediately if there are no events.

If you've tried it and it blocks, then never mind!
